# GET http://localhost:4000/members

POST http://localhost:4000/register
Content-Type: application/json

{
    "name": "Tyler",
    "lastName": "Beckstead",
    "emailAddress": "johnsnow@gmail.com",
    "phoneNumber": "3322323",
    "address": "123 Sesame St",
    "dateOfBirth": "02171995",
    "acceptedTerms": true,
    "guardianName": "ddd",
    "guardianLastName": "",
    "guardianPhoneNumber": "",
    "subscribedToNewsletter": true,
    "memberImage": "32932939299"
}

###

# DELETE http://localhost:3000/members/606e70bce542be89ec6a9af8


###

PATCH http://localhost:3000/members/606e7eeef3a8a9a7ecc3d779
Content-Type: application/json

{
    "name": "Doggie",
    "lastName": "Loves Mongo",
    "memberImage": "2929329sakakd92393e29329"
}



